---
# APT package installation
# Repositories and cache already updated by repositories.yml

- name: Install APT packages
  apt:
    name: "{{ item.name }}{{ item.version | default('') }}"
    state: "{{ item.state | default('present') }}"
    install_recommends: "{{ item.install_recommends | default(false) }}"
  loop: "{{ all_apt_packages }}"
  loop_control:
    label: "{{ item.name }}"
  become: yes
  when: all_apt_packages is defined and all_apt_packages | length > 0
  tags: ['apt']

- name: Upgrade all apt packages
  apt:
    upgrade: safe
  become: yes
  tags: ['apt', 'upgrade']
