---
# APT package installation

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags: ['apt']

- name: Install APT packages
  apt:
    name: "{{ item.name }}{{ item.version | default('') }}"
    state: "{{ item.state | default('present') }}"
    install_recommends: "{{ item.install_recommends | default(false) }}"
  loop: "{{ all_apt_packages }}"
  become: yes
  when: all_apt_packages is defined and all_apt_packages | length > 0
  tags: ['apt']
