---
# Pip (Python) package installation

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  become: yes
  tags: ['pip']

- name: Install Pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
  loop: "{{ all_pip_packages }}"
  when: all_pip_packages is defined and all_pip_packages | length > 0
  tags: ['pip']
