---
# Pip (Python) package installation

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  become: yes
  tags: ['pip']

- name: Ensure pip config directory exists (work profile)
  file:
    path: "{{ ansible_env.HOME }}/.config/pip"
    state: directory
    mode: '0755'
  when: profile == 'work'
  tags: ['pip']

- name: Create pip.conf for work profile (artifactory)
  copy:
    dest: "{{ ansible_env.HOME }}/.config/pip/pip.conf"
    content: |
      [global]
      index-url = https://artifactory.dbgcloud.io/artifactory/api/pypi/pypi.python.org/simple
      trusted-host = pypi.org
          artifactory.dbgcloud.io
      extra-index-url = https://pypi.org/simple
    mode: '0644'
  when: profile == 'work'
  tags: ['pip']

- name: Install Pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
  loop: "{{ all_pip_packages }}"
  when: all_pip_packages is defined and all_pip_packages | length > 0
  tags: ['pip']
